### PR TITLE
Some readability changes

### PR DESCRIPTION
**Pull request by Pebor**
I just pressed random keys, it looks ok but functionaly? :shrug: 
There were inconsistencies about " | " or just "|" so I made it all "|".

### CODE REVIEW

**Comment by con-f-use** [comment]
Sorry, but the correct way to do this is to configure CI to use an auto formatter.

**Comment by Pebor** [comment]
Benni told me to PR, he knew this was just used with a quick plugin. Feel free to delete it! Don't know what the things above are hah

**Comment by con-f-use** [comment]
I'll merge it. What I was saying above is, people will argue over formatting a lot and it will get messed up. In order to avoid that, we should use and automatic tool for formatting code, an "auto-formatter". And that tool should run on every PR by itself, i.e. via CI (continuous integration).

By the way, you can verify, that this PR doesn't actually change anything. No need to try out shortcuts. Just check "Hide whitespace changes" in the diff viewer settings.

image

**Comment by Pebor** [comment]
Oh okay I understand now! Thanks!

**Pull request merged**
