### PR TITLE
slow down event spamming in main loop

### LINKED ISSUE #25: Overlay animation queue makes WM unusable.
While changing the position of overlay the "overlay move orders" can be queued (supposedly infinitely), this can lead to the situation shown in the attached gif. This makes entire WM unresponsive(you can see me trying to change workspace and press some keybindings), and any commands entered while animations are playing are added to queue and get executed all at once after animations are done. If "move orders" are spammed a lot, even the time displayed in the topbar will slowly get late. While spamming "overlay move orders" i probably not an usual use case for what overlay is, i think that it should only accept next "overlay move order" after current has finished, so we can avoid situations where you spam "move orders" and then have to wait 5 minutes in order to do anything.

output

### PR DESCRIPTION
**Pull request by uvera**
Should fix #25 

Event amount might need to be adjusted.

### CODE REVIEW

**Comment by uvera** [comment]
The optimal event queue value with #105 is around 125 events instead of 250

**Comment by paperbenni** [comment]
Is there an instance when this would be needed when we have?
https://github.com/instantOS/instantWM/pull/105

**Comment by con-f-use** [comment]
> The optimal event queue value with #105 merged is around 125 events instead of 250

Doesn't the optimal event rate depend a bit on the hardware you're running on?

**Comment by uvera** [comment]
> Is there an instance when this would be needed when we have?
> #105

Try spamming summon terminal, the `meta + enter` keybind

**Comment by uvera** [comment]
> > The optimal event queue value with #105 merged is around 125 events instead of 250
> 
> Doesn't the optimal event rate depend a bit on the hardware you're running on?

I've no clue to be honest, I've no low performance devices to test that

**Comment by uvera** [comment]
Everything seems fine with master changes, this patchset not needed anymore and it's less preferred over the `master` branch changes due to buggy nature of this implementation.

**Pull request closed without merging**
