### PR TITLE
implement cfacts, only for tiled for now

### PR DESCRIPTION
**Pull request by B4rc1**
This PR basically adds [dwm's cfacts patch](https://dwm.suckless.org/patches/cfacts/), allowing to resize windows in the stack in tiled layouts with a shortcut.
Tiled layout (+ symbol) only for now, as It's the only layout I use, it should be simple tho to apply cfact support to other layouts.
As in #35 we need to think about if we want to speed up/disable animations for this, as it feels kind of laggy on master. On my private branch with speed up animations (`framecount = 3`), it feels pretty smooth tho. 

Excuse the two different B4rc1's in the commit, I had the wrong email set up...

### CODE REVIEW

**Comment by con-f-use** [comment]
Cool. As with https://github.com/instantOS/instantWM/pull/35, I'm not entirely convinced it is worth the extra code and possible bugs / maintenance burde. It's not that much more useful than simply resizing a window, when one needs to. But perhaps there is popular demand.

**Comment by B4rc1** [comment]
> It's not that much more useful than simply resizing a window

You cannot resize windows in tiled while keeping them in tiled, only floating windows.

> I hope you understand that a lean, clean codebase is still a goal and we don't want to add everything

I understand, right now I'm moving from a custom dwm build to instantWM and in the process create PR's for everything that I feel is missing and am implementing for myself on a private branch anyways, so I'm just getting a feel for what could be interesting/useful for you guys.

**Comment by B4rc1** [comment]
yeah **floating** window, I am talking about a tiled window, so windows in the tiled layout

**Comment by con-f-use** [comment]
Sure, but again, by adjusting the master are, you can at least adjust the width.

**Comment by B4rc1** [comment]
This layout/setup is not possible on master:
grafik
after this PR it is

**Comment by con-f-use** [comment]
Yeah, I admit, I thought there was already a shortcut for hight adjustment similar to the width adjust for the master area. My bad, but I got from the start, what you PR's goal was.

**Comment by B4rc1** [comment]
I use it as my main WM and haven't noticed any issues and the way the patch was written makes it pretty much isolated from anything else, only the layout code interacts with it. Floating windows work just fine, so does full screen, overlay (retain their size like floating windows, which can get messy/small but that's not a problem of this PR, since this happens to floating windows too) , tag switching, additionally floating windows also remember which size/cfact they were, so they go right back into the correct/assigned size.

**Pull request closed without merging**
