### PR TITLE
Toggleable focus-follows-mouse

### PR DESCRIPTION
**Pull request by XeroOl**
This pull request adds a new option called `focusfollowsmouse` that lets the user control whether or not the focus follows the mouse. By default, focusfollowsmouse is set to `1`, which is how instantWM normally behaves, where moving the mouse will update the currently focused window. If `focusfollowsmouse` is set to `0`, a left click or right click or middle click is necessary to switch the focus between windows. This makes instantWM behave more like a traditional floating window manager.

The `focusfollowsmouse` option can be set with `instantwmctrl`. To switch off focus following the mouse, run:
```
instantwmctrl focusfollowsmouse 1
```
0 toggles, 1 disables, 2 enables
No hotkeys have been bound, so the setting must be controlled through the command line as of now. I expect that the common use case would be to insert the command into the `autostart.sh` file.

### CODE REVIEW

**Comment by XeroOl** [comment]
I've found a bug with this code, so I'm closing this until I fix it

**Comment by XeroOl** [comment]
I've found the issue and addressed it, so I'm opening the pull request again

**Comment by con-f-use** [comment]
Thanks for the contribution. Please implement this option in [instanwmctrl](https://github.com/instantOS/instantWM/blob/master/instantwmctrl.sh) and document it in its description.

**Comment by XeroOl** [comment]
instantwmctrl works fine without any changes to the source, but I've added `focusfollowsmouse` to the help text. It now reads:
```
Usage: ./instantwmctrl.sh <command> <args>...

Really basic tool to send commands to instantWM.

Commands:
    help                     Display this help text
    overlay
    tag
    animated
    alttab
    layout <number>|<name>   Change window layout to given argument, e.g. ./instantwmctrl.sh layout monocle
    prefix
    focusfollowsmouse        Control if window focus will change with mouse movement
    allttag
    hidetags
```

**Pull request merged**
