### PR TITLE
scratchpad enhancements

### PR DESCRIPTION
**Pull request by B4rc1**
Right now, when opening a scratchpad, the scratchpad window(s) are not focused correctly, unless one is the last window on the monitor, this PR fixes that and additional warps the mouse to that window (personal preference but a sane default i would say, although i would understand a more conservative approach to warping)

### CODE REVIEW

**Comment by B4rc1** [comment]
I apologise for the typo in the commit message (can I change that without breaking everything?)
Okay after using the scratchpad feature some more, I found that having to manually  create scratchpads was very tiring and discouraged the use of them, so I added the feature, that when there are no scratchpads (yet) it creates a new terminal and makes it a scratchpad.
Only problem with this is that the rule to make the window floating does not fit instantWMs terminal agnostic design because `st` is hardcoded in the rules
```
{"St", NULL,     scratchpadname,        0,            1,           -1},
```
I'm not aware of any way to determine the window instance/class dynamically/terminal agnostically.
Some help would be appreciated

**Comment by con-f-use** [comment]
> I apologise [sic] for the typo in the commit message (can I change that without breaking everything?)

Thanks for the PR. No you cannot change the commit message, because you don't have right access to this repo. Changing the commit message would require you to rewrite the commit history. However, it's fine - history editing is usually considered bad practice anyway.

**Comment by con-f-use** [comment]
As for the terminal thing: `~/.config/instantos/default/terminal` is a symlink to what ever the user specified as terminal in the top left corner settings menu under "Default Applications". Use that path.

**Comment by B4rc1** [comment]
yeah the terminal thing, I knew, I spawn the symlink:
```
static const char *termscratchcmd[] = {".config/instantos/default/terminal", "-t", scratchpadname, NULL};
```
the terminal has to support `-t` but all terminals I know of do that. What I'm asking is making a rule to make it floating, as there is no way (as far as I know) to get the terminal class/instance you need for rules only through the name: 
e.g. alacritty (using xprop):
```
WM_CLASS(STRING) = "Alacritty", "Alacritty"
```
kitty (also xprop):
```
WM_CLASS(STRING) = "kitty", "kitty"
```
every terminal does (as far as i can tell) it's own thing in that regard. And making it floating in the `makescratchpad()` function is too late and the  stack/layout will be reordered and only after that the scratchpad will be made floating. Another option is to add a check earlier in `manage()` but that seems like a hack and I want to avoid that. But if it's the only option, I am willing to do that...

**Comment by con-f-use** [comment]
Got you, no, there is not a way, either you have to check for them all or implement a function instantWM that compares it to the symlink and rewrite a few things.

**Comment by B4rc1** [comment]
As it turns out, you can just match the title, regardless of class/title so this should now be fully terminal agnostic, although I did not test it.

**Comment by paperbenni** [comment]
I just implemented your changes into instantWM. I used window classes instead of titles and made some of your stuff shorter, namely the process of creating the scratchpad

**Comment by con-f-use** [comment]
So, this PR can be closed?

**Comment by paperbenni** [comment]
Sorry if I'm not using your exact code but I feel like just verbally describing the changes would take a lot longer than actually doing them xD
From a functionality standpoint it's exactly your PR

**Comment by B4rc1** [comment]
Yes just checked, rebased my custom build onto it and works flawlessly! Thank you for your time!

**Comment by paperbenni** [comment]
The new feature still crashes sometimes so I'll have to fix that

**Comment by paperbenni** [comment]
Fixed most of them, it's working pretty well now

**Pull request closed without merging**
